cc_library(
    name = "intro",
    hdrs = glob(["**/*.hpp"]),
    include_prefix = "intro",
    visibility = ["//visibility:public"],
    deps = [
        "//third_party/json",
        "//third_party/yaml_cpp",
        "//third_party/fmt",
    ],
)
